<?php

namespace WTS_EAE\Modules\ComparisonTable;

use WTS_EAE\Base\Module_Base;

class Module extends Module_Base {

	public function get_widgets() {
		return [
			'ComparisonTable',
		];
	}

	public function get_name() {
		return 'eae-comparisontable';
	}

	public function get_title() {

		return __('Comparison Table', 'wts-eae');

	}

	function add_dependent_js_css() {
		parent::add_dependent_js_css(); // TODO: Change the autogenerated stub
		wp_enqueue_style( 'font-awesome-4-shim');
		wp_enqueue_style( 'font-awesome-5-all');
		wp_enqueue_script( 'font-awesome-4-shim');
	}

}