<?php

namespace WTS_EAE\Modules\FilterableGallery;

use WTS_EAE\Base\Module_Base;

class Module extends Module_Base {

    public function get_widgets() {
        return [
            'FilterableGallery',
        ];
    }

    public function get_name() {
        return 'eae-FilterableGallery';
    }

    function add_dependent_js_css() {
        parent::add_dependent_js_css(); // TODO: Change the autogenerated stub
        wp_enqueue_script( 'masonry');
        wp_enqueue_script( 'wts-isotope');
        wp_enqueue_script( 'wts-tilt' );
    }

}