<?php

namespace WTS_EAE\Modules\ProgressBar\Skins;

use Elementor\Widget_Base;
use Elementor\Controls_Manager;


class Skin_4 extends Skin_Base {

	protected function _register_controls_actions() {
		parent::_register_controls_actions(); // TODO: Change the autogenerated stub
		add_action( 'elementor/element/eae-progress-bar/pb_skins/before_section_end', [
			$this,'extra_controls_add'
		] );
	}

	public function get_id() {
		return 'skin4';
	}

	public function get_title() {
		return __( 'Skin 4', 'wts-eae' );
	}

	public function extra_controls_add() {
	}

	public function register_style_controls() {
		parent::register_style_controls(); // TODO: Change the autogenerated stub
	}

	function render(){
		$this->common_render();
	}
}